### ISSUE TITLE
Dependency install documentation is incomplete

### ISSUE THREAD

**Issue by Ullaakut** [khast3x/Redcloud#4]
Hey again @khast3x,

When attempting to list the available templates, I met a `ModuleNotFoundError`. I then ran the command that was specified in the documentation, which did not work:

![Screenshot 2019-03-17 at 16 51 17](https://user-images.githubusercontent.com/6976628/54493877-fd36bb80-48d4-11e9-99f8-c2664ebcea05.png)

Fortunately, it was just that the file extension was missing! Works like a charm once the file extension is added to the command 👍🏽

The documentation should be updated, though

**Comment by Ullaakut** [comment]
Actually, even with `PyYAML` installed, I'm still getting this error.

```go
[MAIN MENU]
Choose deploy action:
	[1] Deploy redcloud on local machine
	[2] Deploy redcloud on remote ssh machine
	[3] Deploy redcloud on remote docker-machine
	[4] Stop local or docker-machine redcloud deployment
	[5] Stop remote ssh redcloud deployment
	[6] List available templates
	[q] Quit

>> 6
Traceback (most recent call last):
  File "redcloud.py", line 387, in <module>
    menu_deploy_target()
  File "redcloud.py", line 370, in menu_deploy_target
    list_available()
  File "redcloud.py", line 80, in list_available
    import yaml
ModuleNotFoundError: No module named 'yaml'

$ pip list | grep YAML
PyYAML                        5.1
```
